language: node_js
node_js:
  - lts/*

install:
  - npm install

stages:
  - "Airbnb test"
  - "Vue style test"
  - "Unit test"

jobs:
  include:
    - stage: "Airbnb test"
      script: npm run airbnb
    
    - stage: "Vue style test"
      script: npm run vue

    - stage: "Unit test"
      script: npm run test

      # deploy:
      #   provider: npm
      #   email: "chenyihuang001@gmail.com"
      #   api_key: $NPM_USER_TOKEN
      #   on:
      #     branch: master
        
      # after_deploy:
      #  - "echo 'Already deployed!'"
