language: node_js
node_js:
  - lts/*

install:
  - npm install

jobs:
  include:
    - stage: CS test
      script: npm run style
      
    - stage: Unit test
      script: npm run test

      # deploy:
      #   provider: npm
      #   email: "chenyihuang001@gmail.com"
      #   api_key: $NPM_USER_TOKEN
      #   on:
      #     branch: master
        
      # after_deploy:
      #  - "echo 'Already deployed!'"
